plugins = []
headers = []
redirects = []

[build]
edge_functions = "C:\\Users\\david\\Desktop\\ai-roleplay-pwa-development\\netlify\\edge-functions"
publish = "C:\\Users\\david\\Desktop\\ai-roleplay-pwa-development\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/api/llm-proxy"
function = "llm-proxy"

[functions]

[functions."*"]